#!/bin/bash
TODAY=$(date +"%Y-%m-%d")
echo "Teie nimi: "
read name
echo "Teie sünnikuupäev(yyyy-mm-dd)"
read birthdate
tmpDays=$(printf '%s' $( ($(date -u -d"$TODAY" +%s)- $(date -u -d"$birthdate" +%s))) )
age=$((tmpDays / 60 / 60 / 24 / 364 ))
echo $name sa oled $age aastat vana.
