#! /bin/bash
#
# skriptimine 2 oma andmetega
#
# skripti algus
echo "Today is " `date +"%A, %B %d, %Y"`' #Väljastab tänase kuupäeva
echo "Time is "` date +"%H:%M"`'#Väljastab hetke kellaaja
cal #väljastab hetke kuu kalendri
# skript lõpp
